TRACK_CLASSES = {
    "AUTOVÍA": ["Autovia", "Autov.", "A.", "Au.", "Autvía", "Autv"],
    "CALLE": ["C.", "Cl.", "Cl", "Cal.", "Clle.", "Cll.", "C/"],
    "AVENIDA": ["Av.", "Aven.", "Avda.", "Avd.", "Av/"],
    "RONDA": ["Rda.", "R.", "Rnd.", "Rond.", "Rd"],
    "PASEO": ["Pso.", "P.", "Ps.", "Pase.", "P/", "P°", "Pº"],
    "CARRETERA": ["Ctra.", "Carr.", "Ct.", "Carret.", "Carrt"],
    "CAMINO": ["Cam.", "Cm.", "Cno.", "Camn.", "Cam/", "Cmno."],
    "PLAZA": ["Pl.", "Plz.", "Plza.", "Pz.", "Plz/"],
    "PASAJE": ["Psje.", "Pje.", "Pas.", "Pj.", "Psj"],
    "TRAVESÍA": ["Travesia", "Trvs.", "Trv.", "Trva.", "Trav.", "Trav/"],
    "CALLEJÓN": ["Callejon", "Cjón.", "Cjn.", "Callej.", "Clj.", "Cj"],
    "GLORIETA": ["Glta.", "Gta.", "Glor.", "Glt.", "Glori"],
    "COSTANILLA": ["Cost.", "Costl.", "Cstl.", "Cst.", "Costl"],
    "PLAZUELA": ["Plzla.", "Plzuela", "Pzla.", "Plzl", "Plazla"],
    "CUESTA": ["Cta.", "Cst.", "Cu.", "Cst.", "Cta/"],
    "PARTICULAR": ["Part.", "Prt.", "Pt.", "Prtc.", "Partic"],
    "PUENTE": ["Pte.", "Pt.", "Pnt.", "Puent.", "Pnt/"],
    "ACCESO": ["Acc.", "Acs.", "Accs.", "Accso.", "Acc/"],
    "PISTA": ["Pta.", "Pt.", "Pis.", "Pst.", "Pist"],
    "BULEVAR": ["Blvr.", "Bvl.", "Bulev.", "Bul.", "Blv"],
    "ESCALINATA": ["Esc.", "Esca.", "Escl.", "Escn.", "Esct"],
    "PASADIZO": ["Psdz.", "Pzdo.", "Pasdz.", "Pasad.", "Pasdz"],
    "AUTOPISTA": ["Atp.", "Autp.", "Atpst.", "Autpsta.", "Autp"],
    "CAÑADA": ["Cañ.", "Cñ.", "Cnd.", "Cañd.", "Cnd"],
    "CARRERA": ["Carr.", "Cr.", "Cra.", "Crra.", "Crr"],
    "GALERÍA": ["Galeria", "Gal.", "Glr.", "Galr.", "Glería.", "Gal/"],
}


MISSPELLINGS_MADRID = {
    # Old neighborhood names
    "las tablas": "valverde",
    "villaverde alto": "villaverde alto - casco historico de villaverde",
    "pau de carabanchel": "buenavista",
    # Misspellings
    "pena": "peña",
    "r.": "republica",
    "r": "republica",
    "buena vista": "buenavista",
    "dr.": "doctor",
    "dr": "doctor",
    "ortega y gasset": "jose ortega y gasset",
    "valleguerra": "valle guerra",
    "alacala": "alcala",
    "acala": "alcala",
    "asamblea": "asambleas",
    "narvez": "narvaez",
    "sebastian elcano": "juan sebastian elcano",
    "opera": "isabel ii",
    "silvea": "silvela",
    "marques de silvea": "marquesa de silvela",
    "marques de silvela": "marquesa de silvela",
    "marquesa de silvea": "marquesa de silvela",
    "sinancas": "simancas",
    "alzira": "alcira",
    "sainz de baranda": "alcalde sainz de baranda",
    "alcaide sainz de baranda": "alcalde sainz de baranda",
    "alcalde saniz de baranda": "alcalde sainz de baranda",
    "bolanos": "bolaños",
    "müller": "muller",
    "comandante zorita": "aviador zorita",
    "pilicano": "pelicano",
    "odonnell": "o'donnell",
    "odonel": "o'donnell",
    "odonnel": "o'donnell",
    "odonell": "o'donnell",
    "saipan": "isla de saipan",
    "actocha": "atocha",
    "penuelas": "peñuelas",
    "nuno gomez": "nuño gomez",
    "puenteareas": "ponteareas",
    "lopez grasa": "lopez grass",
    "corte del faraon": "la corte de faraon",
    "paravicinos": "paravicino",
    "brcelona": "barcelona",
    "negilla": "neguilla",
    "filosofa simone weill": "filosofa simone weil",
    "colatorao": "calatorao",
    "rutilio gacis": "rutilio gaci",
    "marques de sant ana": "marques de santa ana",
    "doctor primo de rivera": "doctor fernando primo de rivera",
    "bernanrdo": "bernardo",
    "jacinto valaguer": "jacinto verdaguer",
    "pañerias": "pañeria",
    "espiritu sant": "espiritu santo",
    "puerto de ibañetas": "puerto de ibañeta",
    "wad ras": "wad-ras",
    "lluc": "virgen de lluc",
    "mesejos": "los mesejo",
    "joan maragall": "poeta joan maragall",
    "poeta joan maragal": "poeta joan maragall",
    "alto puerto": "puerto alto",
    "lavapiies": "lavapies",
    "seroya": "secoya",
    "sta": "santa",
    "sto": "santo",
    "ona": "oña",
    "tromas": "trompas",
    "los andres": "los andes",
    "oneil": "o'neill",
    "oneill": "o'neill",
    "granon": "grañon",
    "cgdor": "corregidor",
    "francisco javier saenz oi": "francisco javier saenz de oiza",
    "francisco javier saenz oiza": "francisco javier saenz de oiza",
    "Poligono Uzp0204 Los Berrocales": "provisional berrocales setenta y uno",
    "los berrocales": "provisional berrocales setenta y uno",
    "zamenhof": "doctor zamenhof",
    "vistalegre": "vista alegre",
    "vistabella": "vista bella",
    "vicente carball": "vicente carballal",
    "ponts de molins": "pont de molins",
    "barrio malasaña": "manuela malasaña",
    "moscaret": "moscareta",
    "vinamala": "viñamala",
    "cantalejos": "cantalejo",
    "argueso": "argüeso",
    "gutemberg": "gutenberg",
    "villamil": "villaamil",
    "monserrat": "montserrat",
    "mesonero romano": "mesonero romanos",
    "mesoneros romanos": "mesonero romanos",
    "berasategui": "berastegui",
    "rendencion de breda": "rendicion de breda",
    "maquinillas": "maquinilla",
    "urgell": "urgel",
    "sanchez barcaistegui": "sanchez barcaiztegui",
    "concejal granizo": "concejal victorino granizo",
    "albasanzs": "albasanz",
    "yustre": "yuste",
    "agacate": "aguacate",
    "potugal": "portugal",
    "valero": "san valero",
    "lorenzo correa": "lorenza correa",
    "beansain": "beasain",
    "maestro lasalle": "maestro lassalle",
    "muñoz grandes": "marcelino camacho",
    "sambarra": "sambara",
    "gurmescindo": "gumersindo",
    "gumerscindo": "gumersindo",
    "gumercindo": "gumersindo",
    "basteros": "bastero",
    "araiza": "ariza",
    "cabana": "cabaña",
    "alfredo castro gamba": "alfredo castro camba",
    "pinos altas": "pinos alta",
    "san adela": "santa adela",
    "txurruka": "churruca",
    "pablo casalls": "pablo casals",
    "don alvaro de basan": "don alvaro de bazan",
    "don alvaro de bazanº": "don alvaro de bazan",
    "madrilena": "madrileña",
    "madrilejos": "madridejos",
    "caranchel": "carabanchel",
    "falcionelo": "falcinelo",
    "santa rafaela maria del sagrario corazon": "santa rafaela maria del sagrado corazon",
    "fernando sexto": "fernando vi",
    "valderobres": "valderrobres",
    "urquiola": "doctor urquiola",
    "campanilla": "campanillas",
    "encarnacio": "encarnacion",
    "gueteria": "guetaria",
    "madqueda": "maqueda",
    "monasterios de montesclaros": "monasterio de montesclaros",
    "lopez mequia": "lopez mezquia",
    "salsdipuedes": "salsipuedes",
    "m teresa": "maria teresa",
    "comandante fotanes": "comandante fontanes",
    "olviar": "olivar",
    "cardenal cisnero": "cardenal cisneros",
    "alcazaaba": "alcazaba",
    "garrellano": "garellano",
    "viejo de leganes": "camino viejo de leganes",
    "viejo de villaverde": "camino viejo de villaverde",
    "arroyo del fresno": "arroyofresno",
    "general prolier": "general diaz porlier",
    "general yage": "san german",  # Changed recently due to a Francoist reference
    "general yagüe": "san german",
    "general franjul": "las aguilas",
    "lago eire": "lago erie",
    "valle de bergantinos": "valle de bergantiños",
    "ntra.": "nuestra",
    "ntra": "nuestra",
    "sra.": "señora",
    "sra": "señora",
    "senor": "señor",
    "senora": "señora",
    "suances": "suanzes",
    "gimenez": "jimenez",
    "gimenes": "jimenez",
    "jimenes": "jimenez",
    "ramon fernandez hijicos": "rafael fernandez hijicos",
    "francisquita": "doña francisquita",
    "general kirkpatrick": "carlota o'neill",
}
